import os
import json

input_path = "res/json/named_char_refs.json"
output_dir = "crux/parse"
output_file = "named_char_refs_gen.odin"
output_path = os.path.join(output_dir, output_file)

os.makedirs(output_dir, exist_ok=True)

with open(input_path, "r", encoding="utf-8") as f:
    data = json.load(f)

with open(output_path, "w", encoding="utf-8") as f:
    f.write("// Code generated by build script. DO NOT EDIT.\n")
    f.write("// Source: https://html.spec.whatwg.org/multipage/named-characters.html\n\n")
    f.write("package parse\n\n")
    
    f.write("named_char_ref_map: map[string]string\n\n")
    
    f.write("init_html_named_character_references_map :: proc(allocator := context.allocator) {\n")
    f.write(f"    named_char_ref_map = make(map[string]string, {len(data)}, allocator)\n\n")
    
    for k, v in data.items():
        key = k[1:] if k.startswith("&") else k
        
        chars = (v["characters"]
                 .replace("\\", "\\\\")
                 .replace('"', '\\"')
                 .replace("\n", "\\n")
                 .replace("\r", "\\r")
                 .replace("\t", "\\t"))
        
        f.write(f'    named_char_ref_map["{key}"] = "{chars}"\n')
        
    f.write("}\n\n")
    
    f.write("destroy_html_named_character_references_map :: proc() {\n")
    f.write("    delete(named_char_ref_map)\n")
    f.write("}\n")

print(f"Success: Generated {len(data)} entries -> {output_path}")
